Repository tomas-light/food-captain, pull requests merged in 2023-04, with the labels that each got.

#9 Configure client
  .eslintrc.js
  README.md
  application/client/api/jest.config.ts
  application/client/api/package.json
  application/client/api/src/.gitignore
  application/client/api/src/ApiInterceptor.ts
  application/client/api/src/UserApi.ts
  application/client/api/src/base/API_BASE_URL.ts
  application/client/api/src/base/ApiBase.ts
  application/client/api/src/base/ApiResponse.ts
  application/client/api/src/base/ApiResponseStatus.ts
  application/client/api/src/environment.d.ts
  application/client/api/src/index.ts
  application/client/api/src/utils/findErrorMessage.ts
  application/client/api/src/utils/hasServerReturnedErrorPage.test.ts
  application/client/api/src/utils/hasServerReturnedErrorPage.ts
  application/client/api/src/utils/isAxiosError.test.ts
  application/client/api/src/utils/isAxiosError.ts
  application/client/api/tsconfig.json
  application/client/root/package.json
  application/client/root/src/Root.tsx
  application/client/tsconfig.json
  application/server/api/build-scripts/scrab-envs.ts
  application/server/api/package.json
  application/server/api/src/controllers/UserApiController.ts
  application/server/api/src/index.ts
  application/server/api/src/startApi.ts
  application/server/database/Readme.md
  application/server/database/package.json
  application/server/database/src/tables/DishSetTable.ts
  application/server/database/src/tables/DishTable.ts
  application/server/database/src/tables/IngredientSetTable.ts
  application/server/database/src/tables/MenuTable.ts
  application/server/database/src/tables/RecipeTable.ts
  application/server/database/src/tables/ScheduleTable.ts
  application/server/host/package.json
  application/server/tsconfig.json
  package.json
  yarn.lock
Labels: configuration

#16 fix db init cripts
  application/server/database/initPostgresDatabase.sql
  application/server/database/src/postgres/sql/create.sql
  application/server/database/src/postgres/sql/data.sql
Labels: bug, database

#18 feature/multer-api-file-upload-middleware
  .vscode/launch.json
  application/server/api/package.json
  application/server/api/src/controllers/ImageApiController.ts
  application/server/database/src/entities/Image.entity.ts
  yarn.lock
Labels: enhancement

#19 styled navigation panel
  application/client/root/package.json
  application/client/root/src/Layout/NavigationPanel.module.scss
  application/client/root/src/Layout/NavigationPanel.tsx
  application/client/root/src/router.tsx
  application/client/shared/src/colors.scss
  application/client/shared/src/theme.ts
  application/client/shared/src/theme/index.ts
  yarn.lock
Labels: UI

#20 improved common UI
  .vscode/settings.json
  application/client/api/src/LocaleApi.ts
  application/client/root/src/Layout/Layout.tsx
  application/client/root/src/Layout/NavigationBar.module.scss
  application/client/root/src/Layout/NavigationBar.tsx
  application/client/root/src/Layout/NavigationPanel.module.scss
  application/client/root/src/Layout/NavigationPanel.tsx
  application/client/root/src/Layout/index.ts
  application/client/root/src/SomePage.tsx
  application/client/root/src/appInitializer/AppInitializer.tsx
  application/client/root/src/config/i18next/configureTranslation.ts
  application/client/root/src/config/redux/configureRedux.ts
  application/client/root/src/management/ManagementPage.module.scss
  application/client/root/src/management/ManagementPage.tsx
  application/client/root/src/management/index.ts
  application/client/root/src/management/ingredient/AddIngredientPage.module.scss
  application/client/root/src/management/ingredient/AddIngredientPage.tsx
  application/client/root/src/management/ingredient/EditIngredientPage.tsx
  application/client/root/src/management/ingredient/IngredientPage.tsx
  application/client/root/src/management/ingredient/redux/Ingredient.controller.ts
  application/client/root/src/management/ingredient/redux/Ingredient.store.ts
  application/client/root/src/management/ingredient/redux/index.ts
  application/client/root/src/management/macaroni-border.png
  application/client/root/src/router.tsx
  application/client/root/src/routing/appUrls.ts
  application/client/root/static/img/favicon.svg
  application/client/shared/src/atoms/icons/Icon.tsx
  application/client/shared/src/atoms/icons/LogoIcon.tsx
  application/client/shared/src/atoms/icons/MeatBallIcon.tsx
  application/server/api/src/controllers/ImageApiController.ts
  application/server/api/src/controllers/LocaleApiController.ts
  application/server/api/src/locales/en/navigation.json
  application/server/api/src/locales/ru/navigation.json
  yarn.lock
Labels: enhancement, UI

#21 Table management/dishes
  application/client/root/src/Layout/Maeatball Sprite.png
  application/client/root/src/Layout/NavigationPanel.module.scss
  application/client/root/src/Layout/NavigationPanel.tsx
  application/client/root/static/sounds/meatBall_slap.mp3
  application/server/host/src/webpack/config.base.ts
Labels: UI

#22 Implemented and designed ingredients management
  application/client/root/src/App.tsx
  application/client/root/src/Gallery/Gallery.module.scss
  application/client/root/src/Gallery/Gallery.tsx
  application/client/root/src/Gallery/index.ts
  application/client/root/src/management/ManagementPage.module.scss
  application/client/root/src/management/ManagementPage.tsx
  application/client/root/src/management/ingredient/AddIngredientPage.module.scss
  application/client/root/src/management/ingredient/AddIngredientPage.tsx
  application/client/root/src/management/ingredient/EditIngredientPage.tsx
  application/client/root/src/management/ingredient/IngredientPage.tsx
  application/client/root/src/management/ingredient/IngredientPageTemplate.module.scss
  application/client/root/src/management/ingredient/IngredientPageTemplate.tsx
  application/client/root/src/management/ingredient/IngredientsPage.module.scss
  application/client/root/src/management/ingredient/IngredientsPage.tsx
  application/client/root/src/router.tsx
  application/client/shared/package.json
  application/client/shared/src/atoms/Image/Image.module.scss
  application/client/shared/src/atoms/Image/Image.tsx
  application/client/shared/src/atoms/Image/index.ts
  application/client/shared/src/atoms/Typography.tsx
  application/client/shared/src/atoms/icons/Icon.tsx
  application/client/shared/src/atoms/icons/ImageIcon.tsx
  application/client/shared/src/atoms/icons/ImageSearchIcon.tsx
  application/client/shared/src/atoms/icons/NoImageIcon.tsx
  application/client/shared/src/atoms/icons/PlatterIcon.tsx
  application/client/shared/src/atoms/icons/SearchIcon.tsx
  application/client/shared/src/atoms/icons/TitleIcon.tsx
  application/client/shared/src/atoms/index.ts
  application/client/shared/src/chakraTheme.ts
  application/client/shared/src/css-modules.d.ts
  application/client/shared/src/index.ts
  application/client/shared/src/molecules/buttons/Button/Button.tsx
  application/client/shared/src/organisms/fields/ImageField.module.scss
  application/client/shared/src/organisms/fields/ImageField.tsx
  application/client/shared/src/organisms/fields/TextField.module.scss
  application/client/shared/src/organisms/fields/TextField.tsx
  application/server/api/src/locales/en/common.json
  application/server/api/src/locales/en/ingredient.json
  application/server/api/src/locales/ru/common.json
  application/server/api/src/locales/ru/ingredient.json
Labels: enhancement

#25 implemented recipe view mode
  application/client/root/src/management/recipe/RecipeDetailsPage.module.scss
  application/client/root/src/management/recipe/RecipeDetailsPage.tsx
  application/client/root/src/management/recipe/RecipePage.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeIngredients.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeTags.tsx
  application/client/root/src/management/recipe/constants.ts
  application/client/root/src/management/recipe/useRecipe.ts
  application/client/shared/src/chakraTheme.ts
  application/client/shared/src/organisms/fields/RichTextField/RichText.tsx
  application/client/shared/src/organisms/fields/RichTextField/index.ts
  application/server/api/src/locales/en/recipe.json
  application/server/api/src/locales/ru/recipe.json
Labels: UI

#27 Recipe UI fixes
  application/client/root/src/Gallery/Gallery.module.scss
  application/client/root/src/Gallery/Gallery.tsx
  application/client/root/src/Layout/Layout.module.scss
  application/client/root/src/Layout/NavigationPanel.module.scss
  application/client/root/src/Layout/NavigationPanel.tsx
  application/client/root/src/management/recipe/RecipeDetails.tsx
  application/client/root/src/management/recipe/RecipeDetailsPage.module.scss
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeDescription/RecipeDescription.module.scss
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeTemplatePage.module.scss
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeTemplatePage.tsx
  application/client/shared/src/atoms/icons/CompassIcon.tsx
  application/client/shared/src/atoms/icons/Icon.tsx
  application/client/shared/src/atoms/icons/SteeringWheelIcon.tsx
  application/client/shared/src/colors.scss
Labels: bug, UI

#28 Recipe UI fixes
  application/client/root/src/config/redux/configureRedux.ts
  application/client/root/src/management/ManagementPage.tsx
  application/client/root/src/management/recipe/AddRecipePage.tsx
  application/client/root/src/management/recipe/EditRecipePage.tsx
  application/client/root/src/management/recipe/RecipeEditor.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/IngredientsModal/Ingredients/Ingredients.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/IngredientsModal/IngredientsModal.module.scss
  application/client/root/src/management/recipe/RecipeTemplatePage/IngredientsModal/IngredientsModal.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeDescription/DescriptionBlock.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeDescription/RecipeDescription.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeIngredients.tsx
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeTemplatePage.module.scss
  application/client/root/src/management/recipe/RecipeTemplatePage/RecipeTemplatePage.tsx
  application/client/root/src/management/recipe/redux/RecipeEditor.controller.ts
  application/client/shared/src/chakraTheme.ts
  application/client/shared/src/organisms/fields/RichTextField/RichTextField.tsx
  application/client/shared/src/theme.ts
  application/server/api/src/locales/en/recipe.json
  application/server/api/src/locales/ru/recipe.json
Labels: UI

#35 implemented mvp recipe randomizer
  application/client/api/src/RecipeApi.ts
  application/client/root/src/management/recipe/Filters/FiltersBlocks.tsx
  application/client/root/src/management/recipe/RandomRecipePage.module.scss
  application/client/root/src/management/recipe/RandomRecipePage.tsx
  application/client/root/src/management/recipe/RecipesPage.tsx
  application/client/root/src/management/recipe/redux/Recipe.store.ts
  application/client/root/src/management/recipe/redux/RecipeFilters.controller.ts
  application/client/root/src/router.tsx
  application/client/tsconfig.json
  application/server/api/src/controllers/RecipeApiController.ts
  application/server/api/src/locales/en/recipe.json
  application/server/api/src/locales/ru/recipe.json
  application/server/api/src/services/RecipeService.ts
  application/server/database/src/postgres/tables/PgRecipe.ts
  application/server/database/src/tables/RecipeTable.ts
Labels: enhancement, database
